### ISSUE TITLE
extract_assets.py fails if /tmp doesn't exist

### ISSUE THREAD

**Issue by dleehr** [sm64-port/sm64_3ds#26]
On a fresh checkout:
```
docker run --rm --mount type=bind,source="$(pwd)",destination=/sm64 sm64 make VERSION=${VERSION:-us} -j4

extracting actors/blue_coin_switch/blue_coin_switch_side.rgba16.png
deleting /tmp/assetqs2n5qvx
extracting actors/blue_coin_switch/blue_coin_switch_top.rgba16.png
Traceback (most recent call last):
  File "./extract_assets.py", line 286, in <module>
    main()
  File "./extract_assets.py", line 218, in main
    png_file = tempfile.NamedTemporaryFile(prefix="asset", delete=False)
  File "/usr/lib/python3.6/tempfile.py", line 690, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.6/tempfile.py", line 401, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/asset2oh68yut'
Makefile:170: *** Failed to extract assets.  Stop.
```

Fixed by adding `--tmpfs /tmp` to the docker run command

**Comment by mkst** [comment]
I think this is just a weird race condition? I've seen it happen on Windows (msys2), but upon running the command again the problem did not occur.
